"""
geometry/freecad_script.py
==========================
FreeCAD 宏脚本生成器（纯 Python 字符串，无 FreeCAD 运行时依赖）。

根据各构型 geometry.py 的输出字典，生成可在 FreeCAD 内部执行的 Python 宏脚本，
支持三种构型：

- pitot         ：旋转体（BSpline + Revolution）
- external_2d   ：拉伸实体（上下壁 BSpline + Face + Extrude）
- axisymmetric  ：双旋转体（CenterBody + Cowl 各自独立 Revolution）

禁止 import FreeCAD（CLAUDE.md 原则 6、禁止事项）。
所有几何数据均来自输入的 geo_result 字典，本模块不调用气动设计函数。
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import List, Tuple


# ---------------------------------------------------------------------------
# 公开接口
# ---------------------------------------------------------------------------

def generate_freecad_macro(
    inlet_type: str,
    geo_result: dict,
    output_path: str,
) -> str:
    """根据进气道几何结果生成 FreeCAD 宏脚本。

    Parameters
    ----------
    inlet_type : str
        ``"pitot"`` | ``"external_2d"`` | ``"axisymmetric"``。
    geo_result : dict
        各构型 ``geometry.py`` 的输出字典（含型线坐标）。
    output_path : str
        宏脚本写入路径（.py），目录不存在时自动创建。

    Returns
    -------
    str
        完整宏脚本字符串（可直接写入文件并在 FreeCAD 中执行）。

    Raises
    ------
    ValueError
        inlet_type 不合法或 geo_result 缺少必要键。
    """
    _BUILDERS = {
        "pitot":       _build_pitot_macro,
        "external_2d": _build_external_2d_macro,
        "axisymmetric": _build_axisymmetric_macro,
    }
    if inlet_type not in _BUILDERS:
        raise ValueError(
            f"inlet_type 须为 'pitot'、'external_2d' 或 'axisymmetric'，"
            f"当前 '{inlet_type}'。"
        )

    macro_str = _BUILDERS[inlet_type](geo_result)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(macro_str)

    return macro_str


# ---------------------------------------------------------------------------
# 通用宏头部 / 尾部模板
# ---------------------------------------------------------------------------

def _header(inlet_type: str) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"# FreeCAD Macro — generated by supersonic_inlet_design\n"
        f"# Inlet type: {inlet_type}\n"
        f"# Generated: {ts}\n"
        f"\n"
        f"import FreeCAD, Part, FreeCADGui\n"
        f"from FreeCAD import Base\n"
        f"\n"
        f'doc = FreeCAD.newDocument("{inlet_type}_inlet")\n'
        f"\n"
    )


def _footer() -> str:
    return (
        "\n"
        "doc.recompute()\n"
        "FreeCADGui.ActiveDocument.ActiveView.fitAll()\n"
    )


# ---------------------------------------------------------------------------
# 坐标序列 → Python 列表字符串
# ---------------------------------------------------------------------------

def _pts_to_str(pts: List[Tuple[float, float]], var: str, is_3d: bool = False) -> str:
    """将 (x, r/y) 型线点列表转为 Python 赋值语句字符串。

    Parameters
    ----------
    pts : list of (float, float)
    var : str
        变量名
    is_3d : bool
        若 True，生成 Base.Vector(x, r, 0) 列表（FreeCAD 3D 点）；
        否则生成 Base.Vector(x, r, 0)（也适用于 Revolution 母线）。
    """
    lines = [f"{var} = ["]
    for x, r in pts:
        lines.append(f"    Base.Vector({x:.10g}, {r:.10g}, 0),")
    lines.append("]")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# pitot：旋转体
# ---------------------------------------------------------------------------

def _build_pitot_macro(geo: dict) -> str:
    if "profile" not in geo:
        raise ValueError("geo_result 缺少 'profile' 键（pitot 构型）。")

    profile = geo["profile"]
    pts_str = _pts_to_str(profile, "profile_pts")

    body = (
        _header("pitot")
        + "# --- 母线坐标点（x, r 平面，绕 x 轴旋转）---\n"
        + pts_str + "\n\n"
        + "# --- 构建 BSpline 母线曲线 ---\n"
        + "bspline = Part.BSplineCurve()\n"
        + "bspline.interpolate(profile_pts)\n"
        + "edge = bspline.toShape()\n\n"
        + "# --- 旋转体（绕 x 轴 360°）---\n"
        + "axis_dir = Base.Vector(1, 0, 0)\n"
        + "axis_pt  = Base.Vector(0, 0, 0)\n"
        + "shell = edge.revolve(axis_pt, axis_dir, 360)\n\n"
        + "# --- 添加到文档 ---\n"
        + 'obj = doc.addObject("Part::Feature", "PitotInlet")\n'
        + "obj.Shape = shell\n"
        + "Part.show(shell)\n"
        + _footer()
    )
    return body


# ---------------------------------------------------------------------------
# external_2d：拉伸板状实体
# ---------------------------------------------------------------------------

def _build_external_2d_macro(geo: dict) -> str:
    for key in ("profile_upper", "profile_lower"):
        if key not in geo:
            raise ValueError(f"geo_result 缺少 '{key}' 键（external_2d 构型）。")

    upper = geo["profile_upper"]
    lower = geo["profile_lower"]

    pts_upper = _pts_to_str(upper, "pts_upper")
    pts_lower = _pts_to_str(lower, "pts_lower")

    # 前缘竖线：upper[0] → lower[0]；出口竖线：upper[-1] → lower[-1]
    x_le, y_le_up = upper[0]
    _, y_le_lo = lower[0]
    x_ex, y_ex_up = upper[-1]
    _, y_ex_lo = lower[-1]

    body = (
        _header("external_2d")
        + "# --- 上壁坐标点 ---\n"
        + pts_upper + "\n\n"
        + "# --- 下壁坐标点 ---\n"
        + pts_lower + "\n\n"
        + "# --- 构建上壁 BSpline ---\n"
        + "bs_upper = Part.BSplineCurve()\n"
        + "bs_upper.interpolate(pts_upper)\n"
        + "edge_upper = bs_upper.toShape()\n\n"
        + "# --- 构建下壁 BSpline ---\n"
        + "bs_lower = Part.BSplineCurve()\n"
        + "bs_lower.interpolate(pts_lower)\n"
        + "edge_lower = bs_lower.toShape()\n\n"
        + "# --- 前缘竖线 ---\n"
        + f"edge_le = Part.makeLine(\n"
        + f"    Base.Vector({x_le:.10g}, {y_le_up:.10g}, 0),\n"
        + f"    Base.Vector({x_le:.10g}, {y_le_lo:.10g}, 0)\n"
        + ")\n\n"
        + "# --- 出口竖线 ---\n"
        + f"edge_ex = Part.makeLine(\n"
        + f"    Base.Vector({x_ex:.10g}, {y_ex_up:.10g}, 0),\n"
        + f"    Base.Vector({x_ex:.10g}, {y_ex_lo:.10g}, 0)\n"
        + ")\n\n"
        + "# --- 封闭截面 Wire & Face ---\n"
        + "wire = Part.Wire([edge_upper, edge_ex, edge_le, edge_lower])\n"
        + "face = Part.Face(wire)\n\n"
        + "# --- 沿 z 轴拉伸（单位展宽 W=1.0 m，可按需修改）---\n"
        + "W = 1.0  # 展向宽度（m）\n"
        + "extrude_vec = Base.Vector(0, 0, W)\n"
        + "solid = face.extrude(extrude_vec)\n\n"
        + "# --- 添加到文档 ---\n"
        + 'obj = doc.addObject("Part::Feature", "External2DInlet")\n'
        + "obj.Shape = solid\n"
        + "Part.show(solid)\n"
        + _footer()
    )
    return body


# ---------------------------------------------------------------------------
# axisymmetric：双旋转体（CenterBody + Cowl）
# ---------------------------------------------------------------------------

def _build_axisymmetric_macro(geo: dict) -> str:
    for key in ("profile_cb", "profile_cowl"):
        if key not in geo:
            raise ValueError(f"geo_result 缺少 '{key}' 键（axisymmetric 构型）。")

    profile_cb = geo["profile_cb"]
    profile_cowl = geo["profile_cowl"]

    pts_cb = _pts_to_str(profile_cb, "pts_cb")
    pts_cowl = _pts_to_str(profile_cowl, "pts_cowl")

    body = (
        _header("axisymmetric")
        + "axis_dir = Base.Vector(1, 0, 0)\n"
        + "axis_pt  = Base.Vector(0, 0, 0)\n\n"
        + "# --- 中心锥母线坐标点 ---\n"
        + pts_cb + "\n\n"
        + "# --- CenterBody：BSpline + Revolution ---\n"
        + "bs_cb = Part.BSplineCurve()\n"
        + "bs_cb.interpolate(pts_cb)\n"
        + "edge_cb = bs_cb.toShape()\n"
        + "shape_cb = edge_cb.revolve(axis_pt, axis_dir, 360)\n\n"
        + "obj_cb = doc.addObject(\"Part::Feature\", \"CenterBody\")\n"
        + "obj_cb.Shape = shape_cb\n"
        + "Part.show(shape_cb)\n\n"
        + "# --- Cowl 内壁母线坐标点 ---\n"
        + pts_cowl + "\n\n"
        + "# --- Cowl：BSpline + Revolution ---\n"
        + "bs_cowl = Part.BSplineCurve()\n"
        + "bs_cowl.interpolate(pts_cowl)\n"
        + "edge_cowl = bs_cowl.toShape()\n"
        + "shape_cowl = edge_cowl.revolve(axis_pt, axis_dir, 360)\n\n"
        + "obj_cowl = doc.addObject(\"Part::Feature\", \"Cowl\")\n"
        + "obj_cowl.Shape = shape_cowl\n"
        + "Part.show(shape_cowl)\n"
        + _footer()
    )
    return body
